# Minimal PEP 518 pyproject file
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
process_sar_wind = "sarwind.script.process_sar_wind:_main"
