@startuml sarwind-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()
'LAYOUT_LEFT_RIGHT()

System_Ext(nbs, "NBS", "Norwegian ground segment for Sentinel data.")
SystemDb_Ext(met_storage, "Data storage", "Lustre file system.")

System(broker, "Broker", "Broker system to listen for messages about new SAR datasets and start SAR wind processing chain. Probably only requires the MMD data access field. Implemented in cron/bash/python.")

System_Boundary(sarwind, "SAR wind"){

  Container(hh2vv, "HH2VV function", "Python", "Convert from HH to VV polarization, using PR from Lin Ren, Jingsong Yang, Alexis Mouche, et al. (2017; remote sensing).")
  Container(nansat, "Nansat software", "Python", "Reads and calibrates SAR data in SAFE format to sigma nought, generates full resolution incidence angles etc. Also reads any NetCDF-CF compliant data, such as Arome-Arctic.")
  Container(swbroker, "Broker", "Python", "Organizes the wind processing workflow.")

  Container(flagger, "Flagging tool", "Python", "Flags pixels with large deviations from other source wind fields (e.g., models, scatterometers)")

}

Rel(broker, sarwind, "starts SAR wind processing in")

Rel(sarwind, broker, "returns filename to")
Rel(swbroker, nbs, "uses geolocation tool for SAFE files in")

Rel(sarwind, met_storage, "stores result file (NetCDF-CF) in")

SHOW_LEGEND()

@enduml
